version: '3.7'
services:
  caddy:
    container_name: caddy_server
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    environment:
      - CADDY_INGRESS_NETWORKS=tanspaces
    networks:
      - tanspaces
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  whoami:
    container_name: caddy_whoami
    image: containous/whoami
    networks:
      - tanspaces
    labels:
      caddy: localhost:8081, ${HOSTNAME}:8081
      caddy.handle_path: /whoami/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams}}"
      caddy.tls: "internal"

volumes:
  caddy_data: {}

networks:
  tanspaces:
    external: true
