version: '3.7'
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  whoami:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: localhost:8081, ${HOSTNAME}:8081
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

volumes:
  caddy_data: {}

networks:
  caddy:
    external: true
